name: Send ticket email on new order

on:
  push:
    paths:
      - 'data/registro.json'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get last order from registro.json
        id: last_order
        run: |
          ORDER=$(jq -r '.[-1]' data/registro.json)
          echo "ORDER_JSON=$ORDER" >> $GITHUB_ENV
          echo "Último pedido:"
          echo "$ORDER"

      - name: Send email with Brevo SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Nuevo pedido en Ana Katana 🛍️"
          from: ${{ secrets.ORDER_EMAIL_FROM }}
          to: ${{ secrets.ORDER_EMAIL_TO }}
          content_type: text/plain
          body: |
            Nuevo pedido recibido 🎉

            ${{ env.ORDER_JSON }}

            📦 Revisa el archivo registro.json para más detalles.