name: Notificación de Nuevo Pedido a Telegram

on: 
  push:
    branches: 
      - main # o la rama principal de tu repositorio
    paths:
      - 'data/registro.json'

jobs:
  send_telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Construir mensaje para Telegram
        id: build_message
        run: |
          # Asegúrate de que jq esté instalado
          sudo apt-get update && sudo apt-get install -y jq

          # Extraer el último pedido de registro.json
          LAST_ORDER=$(jq '.[-1]' data/registro.json)
          ORDER_ID=$(echo "$LAST_ORDER" | jq -r '.id')
          CUSTOMER_EMAIL=$(echo "$LAST_ORDER" | jq -r '.direccion.email')
          TOTAL=$(echo "$LAST_ORDER" | jq -r '.total')

          # ----------------------------------------------------------------------
          # CAMBIO: Bucle corregido para acumular productos y formato simplificado
          # ----------------------------------------------------------------------
          PRODUCTS_TEXT=""
          while read -r line; do
            PRODUCTS_TEXT+="$line"$'\n'
          done < <(echo "$LAST_ORDER" | jq -r '.carrito[] | "\(.nombre)\(if .talla then " (talla " + (.talla|tostring|sub("^talla\\s+";"")) + ")" else "" end) x" + (.cantidad|tostring)')

          MESSAGE="*📦 Pedido #${ORDER_ID} recibido en Ana Katana 📦*\n\n"
          MESSAGE+="*Productos:*\n"
          MESSAGE+="${PRODUCTS_TEXT}"
          MESSAGE+="\n\n*Total:* €${TOTAL} | *Cliente:* ${CUSTOMER_EMAIL}"

          # Usar un delimitador para pasar el mensaje multi-línea
          echo "MESSAGE<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Enviar notificación a Telegram
        run: |
          curl -s -X POST \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="${{ steps.build_message.outputs.MESSAGE }}" \
            -d parse_mode="Markdown"
